### PR TITLE
push: unify clone and pull func

### PR DESCRIPTION
**Pull request by Divyanshu-Modi**

### CODE REVIEW

**Comment by Divyanshu-Modi** [comment]
Might just help for push part as well

**Review by beakthoven — APPROVED** [review]
Decent change, Seems good to me.

**Comment by beakthoven** [comment]
Similar simplification can be done over [here](https://github.com/Neutron-Toolchains/clang-build/blob/main/utils.sh#L106-L136) as well. We can merge clone/pull functions in one for both of them.

**Comment by Divyanshu-Modi** [comment]
Yes, lemme try a commonized func for fetch both binutils and llvm utils

**Comment by beakthoven** [comment]
> Yes, lemme try a commonized func for fetch both binutils and llvm utils

I am currently working on adding shallow clone support in a commonized git function, So i would suggest to wait for my change.

**Pull request merged**
